name: build-lite

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'

      - name: Install minimal R packages
        run: |
          R -e "install.packages(c('tidyverse','mgcv','vegan','MASS','broom'), repos='https://cloud.r-project.org')"

      - name: Render book (HTML only)
        run: quarto render book/ --to html

      - name: Render slides (HTML revealjs)
        run: |
          for d in slides/*; do
            if [ -d "$d" ]; then
              quarto render "$d" --to revealjs
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            book/_book/**
            slides/**/**.html
        if-no-files-found: ignore
