name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'
      - name: Install renv & restore
        run: |
          R -e "install.packages('renv', repos='https://cloud.r-project.org')"
          R -e "renv::init(bare=TRUE); renv::restore()"
      - name: Render book
        run: quarto render book/
      - name: Render slides
        run: |
          for d in slides/*; do
            if [ -d "$d" ]; then
              quarto render "$d"
            fi
          done
      - name: Knit assignments (solutions only as smoke tests)
        run: |
          R -e "print('Knitting assignment solutions…')"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            book/_book/**
            slides/**/**/*.pptx
